# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SnapshotViews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SnapshotViews

  target 'SnapshotViewsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'iOSSnapshotTestCase' 
  end

  target 'SnapshotViewsUITests' do
    # Pods for testing
  end

end
