# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SnapshotTesting' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SnapshotTesting

  target 'SnapshotTestingTests' do
    inherit! :search_paths
    # Pods for testing
  pod 'iOSSnapshotTestCase'
  end

  target 'SnapshotTestingUITests' do
    # Pods for testing
  end

end
