# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SSLPinningExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SSLPinningExample
  pod 'RxSwift'
  pod 'Alamofire', '~> 5.0.0-beta.5'
  target 'SSLPinningExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SSLPinningExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
