# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FavouriteProjectsSection' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FavouriteProjectsSection
  pod 'SDWebImage', '~> 5.0'

  target 'FavouriteProjectsSectionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FavouriteProjectsSectionUITests' do
    # Pods for testing
  end

end
