# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'NamespacingUsingOneModule' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'IntFrameworkOne', :path => '/Users/stevencurtis/Documents/Interviewprep/MediumPosts/Namespacing/Code/IntFrameworkOne'


  # Pods for NamespacingUsingOneModule

  target 'NamespacingUsingOneModuleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NamespacingUsingOneModuleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
