# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrackMyMovement' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
      pod 'GoogleMaps'


  # Pods for TrackMyMovement
        pod 'RxSwift'
      pod 'RxCocoa'


  target 'TrackMyMovementTests' do
    inherit! :search_paths
    # Pods for testing
          pod 'RxTest'
      pod 'RxBlocking'
  end

  target 'TrackMyMovementUITests' do
    # Pods for testing
  end

end
