# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LocalizePods' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LocalizePods
    source 'https://github.com/CocoaPods/Specs.git'
    pod 'Localize-Swift', '~> 2.0'
  target 'LocalizePodsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LocalizePodsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
